flaskpage/routes.py
from datetime import datetime
from flask import render_template, url_for, flash, abort, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskpage import db, bcrypt
from flaskpage.models import User, Homework, DoneHomework, Stats
from flaskpage.utils import save_picture, send_reset_email, send_remainder_email
from flaskpage.forms import (PostForm, RegistrationForm, LoginForm,
							UpdateAccountForm, RequestResetForm, ResetPasswordForm)

postsBP = Blueprint('posts', __name__)
usersBP = Blueprint('users', __name__)
mainBP = Blueprint('main', __name__)
errorsBP = Blueprint('errors', __name__)


@mainBP.route("/about")
def about():
	return render_template('about.html', title='About')

@mainBP.route("/stats")
def stats():
	userNum = User.query.count()
	adminNum = User.query.filter_by(op=True).count()
	postNum = Homework.query.count()
	donehwNum = Stats.query.get(0).comp_hw
	yearhwNum = DoneHomework.query.count()
	remeNum = Stats.query.get(0).sent_rem
	actiUse = User.query.filter_by(op=False).all()
	actiNum = 0
	for Use in actiUse:
		if (datetime.utcnow()-Use.last_seen).days <= 5:
			actiNum += 1
	return render_template('stats.html', title='Statistics', userNum=userNum, remeNum=remeNum, yearhwNum=yearhwNum,
					adminNum=adminNum, postNum=postNum, donehwNum=donehwNum, actiNum=actiNum)

@usersBP.route("/users", methods=['GET', 'POST'])
def users():
	if not current_user.op:
		return redirect(url_for('main.about'))
	else:
		form = RegistrationForm()
		page = request.args.get('page', 1, type=int)
		users = User.query.order_by(User.username.desc()).paginate(page=page, per_page=20)
		if form.validate_on_submit():
			hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
			user = User(username=form.username.data, email=form.email.data, subj=form.subj.data, year=form.year.data, op=form.op.data, password=hashed_password)
			db.session.add(user)
			db.session.commit()
			flash('Account has been created successfully!', 'success')
			return redirect(url_for('users.users'))
		return render_template('users.html', AllUsers=users, title='Users', form=form)

@usersBP.route("/account/<int:user_id>", methods=['GET', 'POST'])
@login_required
def account(user_id):
	if not current_user.op and current_user.id != user_id:
		return redirect(url_for('main.about'))
	else:
		user = User.query.filter_by(id=user_id).first_or_404()
		form = UpdateAccountForm()
		form.user_id = user_id
		if form.validate_on_submit():
			if user.subj != form.subj.data or user.year != form.year.data:
				done_hw = DoneHomework.query.filter_by(user_id=user_id).first()
				while done_hw:
					db.session.delete(done_hw)
					done_hw = DoneHomework.query.filter_by(user_id=user_id).first()
			if form.picture.data:
				picture_file = save_picture(form.picture.data)
				user.image_file = picture_file
			user.username = form.username.data
			user.email = form.email.data
			user.subj = form.subj.data
			user.year = form.year.data
			user.op = form.op.data
			db.session.commit()
			flash('Account has been updated!', 'success')
			return redirect(url_for('users.account', user_id=user.id))
		elif request.method == 'GET':
			form.username.data = user.username
			form.email.data = user.email
			form.subj.data = user.subj
			form.year.data = user.year
			form.op.data = user.op
		image_file = url_for('static', filename='profile_pics/' + user.image_file)
		page = request.args.get('page', 1, type=int)
		comp_hw = DoneHomework.query
		user_hw = User.query
		if user.op:
			posts = Homework.query.filter_by(user_id=user.id)\
							.order_by(Homework.date_posted.desc())\
							.paginate(page=page, per_page=20)
		else:
			posts = Homework.query.filter_by(subj=user.subj)\
							.filter_by(year=user.year)\
							.order_by(Homework.date_posted.desc())\
							.paginate(page=page, per_page=20)
		return render_template('account.html', title='Account', posts=posts, comp_hw=comp_hw,
								user=user, user_hw=user_hw, image_file=image_file, form=form)

@usersBP.route("/user/<int:user_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
	user = User.query.filter_by(id=user_id).first_or_404()
	if not current_user.op and current_user.id != user_id:
		abort(403)
	post = Homework.query.filter_by(user_id=user_id).first()
	while post:
		done_hw = DoneHomework.query.filter_by(homework_id=post.id).first()
		while done_hw:
			db.session.delete(done_hw)
			done_hw = DoneHomework.query.filter_by(homework_id=post.id).first()
		db.session.delete(post)
		post = Homework.query.filter_by(user_id=user_id).first()
	db.session.delete(user)
	db.session.commit()
	flash('User has been deleted!', 'success')
	return redirect(url_for('users.users'))

@mainBP.route("/")
@mainBP.route("/homework", methods=['GET', 'POST'])
@login_required
def homework():
	form = PostForm()
	if form.validate_on_submit():
		post = Homework(user_id=current_user.id, title=form.title.data, subj=form.subj.data, year=form.year.data, content=form.content.data)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created!', 'success')
		return redirect(url_for('main.homework'))
	page = request.args.get('page', 1, type=int)
	if current_user.op:
		posts = Homework.query.filter_by(user_id=current_user.id)\
						.order_by(Homework.date_posted.desc())\
						.paginate(page=page, per_page=20)
	else:
		posts = Homework.query.filter_by(subj=current_user.subj)\
						.filter_by(year=current_user.year)\
						.order_by(Homework.date_posted.desc())\
						.paginate(page=page, per_page=20)
	comp_hw = DoneHomework.query
	user_hw = User.query
	return render_template('homework.html', posts=posts, user_hw=user_hw, title='Homework',
						   form=form, comp_hw=comp_hw, legend='Add Homework')

@postsBP.route("/post/<int:post_id>")
def post(post_id):
	if not current_user.op:
		abort(403)
	post = Homework.query.get_or_404(post_id)
	Users = User.query.filter_by(subj=post.subj, year=post.year, op=False).all()
	done_hw = DoneHomework.query.filter_by(homework_id=post.id)
	data_count = DoneHomework.query.filter_by(homework_id=post.id).count()
	data_total = User.query.filter_by(subj=post.subj, year=post.year).count()
	return render_template('post.html', title='Homework', Users=Users, done_hw=done_hw,
							data_count=data_count, data_total=data_total, post=post)

@postsBP.route("/post/<int:post_id>/<int:user_id>")
def post_done(post_id, user_id):
	post = Homework.query.get_or_404(post_id)
	if not current_user.op or post.author.id != current_user.id:
		abort(403)
	done_hv = DoneHomework.query.filter_by(user_id=user_id, homework_id=post_id).first()
	if done_hv:
		db.session.delete(done_hv)
		Stats.query.get(0).comp_hw -= 1
		db.session.commit()
	else:
		done_hv = DoneHomework(user_id=user_id, homework_id=post_id)
		db.session.add(done_hv)
		Stats.query.get(0).comp_hw += 1
		db.session.commit()
	return redirect(url_for('posts.post', post_id=post_id))

@postsBP.route("/post/<int:post_id>/remainders", methods=['GET', 'POST'])
@login_required
def send_remainders(post_id):
	post = Homework.query.get_or_404(post_id)
	if not current_user.op or post.author.id != current_user.id:
		abort(403)
	users = User.query.filter_by(subj=post.subj, year=post.year, op=False).all()
	for user in users:
		send_remainder_email(user.email, post.title, post.content)
		Stats.query.get(0).sent_rem += 1
		db.session.commit()
	flash(f'Remainders for post {post.title} has been sent!', 'success')
	return redirect(url_for('main.homework'))

@postsBP.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Homework.query.get_or_404(post_id)
	if not current_user.op or post.author.id != current_user.id:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		if post.subj != form.subj.data or post.year != form.year.data:
			done_hw = DoneHomework.query.filter_by(homework_id=post_id).first()
			while done_hw:
				db.session.delete(done_hw)
				done_hw = DoneHomework.query.filter_by(homework_id=post_id).first()
		post.title = form.title.data
		post.subj = form.subj.data
		post.year = form.year.data
		post.content = form.content.data
		db.session.commit()
		flash('Your post has been updated!', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.subj.data = post.subj
		form.year.data = post.year
		form.content.data = post.content
	return render_template('edit_post.html', title='Homework',
						   form=form, legend='Update Post')

@postsBP.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
	post = Homework.query.get_or_404(post_id)
	if not current_user.op or post.author.id != current_user.id:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted!', 'success')
	return redirect(url_for('main.homework'))

@usersBP.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.homework'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			user.last_seen = datetime.utcnow()
			db.session.commit()
			return redirect(next_page) if next_page else redirect(url_for('main.homework'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')
	return render_template('login.html', title='Login', form=form)

@usersBP.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.about'))

@usersBP.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.homework'))
	form = RequestResetForm()
	if form.validate_on_submit():

flaskpage/templates/base.html
<!DOCTYPE html>
<html>
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

		{% if title %}
			<title>ViA Helper - {{ title }}</title>
		{% else %}
			<title>ViA Helper</title>
		{% endif %}
</head>
<body>
	<nav class="navbar-dark bg-success fixed-top">
	 	<div role="main" class="navbar-expand-md container pb-2 pt-2">
			<div class="row pl-3 pr-3">
				<ul class="navbar-nav d-flex mr-auto">
					<li class="nav-item">
						<a href="/homework" title="Sākums" class="site-logo">
						<img class="" height="44px" style="width: 200px" src="https://www.va.lv/themes/via/logo.svg" onerror="this.src='https://id.va.lv/via_header/via_logo.png'">
						</a>
					</li>
				</ul>
				<ul class="navbar-nav">
					<li class="nav-item">
						<button class="nav-item navbar-toggler" type="button" data-toggle="collapse" data-target="#x" aria-expanded="true">
						<span class="navbar-toggler-icon"></span>
						</button>
					</li>
				</ul>
				<div class="navbar-collapse collapse" id="x">
					<div class="row container m-0 p-0">
						<ul class="navbar-nav mr-auto">
							<li class="nav-item">
								<a class="nav-link {% if title=='About' %} active {% endif %} mr-auto" href="{{ url_for('main.about') }}">About</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if title=='Statistics' %} active {% endif %} mr-auto" href="{{ url_for('main.stats') }}">Statistics</a>
							</li>
							{% if current_user.is_authenticated %}
								<li class="nav-item navbar-nav">
								<a class="nav-link {% if title=='Homework' %} active {% endif %} mr-auto" href="{{ url_for('main.homework') }}">Homework</a>
								</li>
								{% if current_user.op==True %}
								<li class="nav-item">
									<a class="nav-link {% if title=='Users' %} active {% endif %} mr-auto" href="{{ url_for('users.users') }}">Users</a>
								</li>
								{% endif %}
							{% endif %}
						</ul>
						<ul class="navbar-nav">
							{% if current_user.is_authenticated %}
								<li class="nav-item">
									<a class="nav-link {% if title=='Account' %} active {% endif %}" href="{{ url_for('users.account', user_id=current_user.id) }}">Account</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
								</li>
							{% else %}
								<li class="nav-item">
									<a class="nav-link {% if title=='Login' %} active {% endif %}" href="{{ url_for('users.login') }}">Login</a>
								</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>
	 	</div>
	</nav>
	<main class="container">
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category, message in messages %}
				<div class="alert alert-{{ category }}">
					{{ message }}
				</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
		{% block content %}{% endblock %}
	</main>


		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskpage/templates/homework.html
{% extends "base.html" %}
{% block content %}
	{% if current_user.op %}
		<div class="content-section">
			<form class="container" method="POST" action="">
				{{ form.hidden_tag() }}
				<fieldset class="form-group mb-1 row">
					<legend class="border-bottom mb-4">Add Homework</legend>

					<div class="row">
						<div class="form-group col-sm-12 col-lg-10 col-xl-8">
							{{ form.title.label(class="form-control-label mb-1") }}
							{% if form.title.errors %}
								{{ form.title(class="form-control form-control-lg is-invalid p-1") }}
								<div class="invalid-feedback">
									{% for error in form.title.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ form.title(class="form-control form-control-lg p-1") }}
							{% endif %}
						</div>
						<div class="form-group col-sm-8 col-lg-6 col-xl-5">
							{{ form.subj.label(class="form-control-label mb-1") }}
							{% if form.subj.errors %}
								{{ form.subj(class="form-control form-control-lg is-invalid p-1") }}
								<div class="invalid-feedback">
									{% for error in form.subj.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ form.subj(class="form-control form-control-lg p-1") }}
							{% endif %}
						</div>
						<div class="form-group col-sm-4 col-lg-4 col-xl-3">
							{{ form.year.label(class="form-control-label mb-1") }}
							{% if form.year.errors %}
								{{ form.year(class="form-control form-control-lg is-invalid p-1") }}
								<div class="invalid-feedback">
									{% for error in form.year.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ form.year(class="form-control form-control-lg p-1") }}
							{% endif %}
						</div>
						<div class="form-group col-sm-12 col-lg-10 col-xl-8">
							{{ form.content.label(class="form-control-label mb-1") }}
							{% if form.content.errors %}
								{{ form.content(class="form-control form-control-lg is-invalid p-1") }}
								<div class="invalid-feedback">
									{% for error in form.content.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ form.content(class="form-control form-control-lg p-1", rows="4") }}
							{% endif %}
						</div>
					</div>
					
				</fieldset>
				<div class="form-group row">
						{{ form.submit(class="btn btn-outline-info") }}
				</div>
			</form>
		</div>
	{% endif %}
	{% for post in posts.items %}
		{% if current_user.op %}
			{% set data_count = comp_hw.filter_by(homework_id=post.id).count() %}
			{% set data_total = user_hw.filter_by(subj=post.subj, year=post.year).count() %}
			<article class="media content-section">
		{% else %}
			{% set is_comp = comp_hw.filter_by(user_id=current_user.id, homework_id=post.id).count() %}
			<article class="media content-section" {% if is_comp == 1 %}style="background-color:#88FF88;"{% else %}style="background-color:#FF6677;"{% endif %}>
		{% endif %}
			<div class="w-100">
				<div class="media">
					<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
					<div class="article-metadata w-100 align-self-center">
						<div class="col-auto row">
							<a class="mr-2 text-primary"{% if current_user.op %} href="{{ url_for('users.account', user_id=post.author.id) }}"{% endif %}>{{ post.author.username }}</a>
							<small class="text-dark" style="padding-top: 3px;">Joined on: {{ post.author.year }}</small>
						</div>
						{% if post.author == current_user %}
							<button type="button" class="btn btn-success btn-sm m-0 mb-1" data-toggle="modal" data-target="#remainderModal{{ post.id }}">Send remainders</button>
							<a class="btn btn-primary btn-sm m-0 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
							<button type="button" class="btn btn-danger btn-sm m-0 mb-1" data-toggle="modal" data-target="#deleteModal{{ post.id }}">Delete</button>
						{% endif %}
					</div>
				</div>
				<h2 class=""><a class="article-title"{% if current_user.op %} href="{{ url_for('posts.post', post_id=post.id) }}"{% endif %}>{{ post.title }}</a></h2>
				<p class="article-content mb-1">{{ post.content }}</p>
				<div class="container pl-0 pr-0">
					<small class="text-dark">Posted on: {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
				<div class="container pl-0 pr-0">
					<small class="text-dark">On subject: {{ post.author.subj }}</small>
				</div>
				<div class="container pl-0 pr-0">
					{% if current_user.op %}
						<small class="text-dark">Completed by: {{ data_count }} of {{ data_total }} student{% if data_total > 1 %}s{% endif %}</small>
					{% else %}
						<small class="text-dark">Completion status: {% if is_comp == 0 %}Not {% endif %}Completed</small>
					{% endif %}
				</div>
			</div>
		</article>
		<!-- Modal -->
		<div class="modal fade" id="remainderModal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Are you sure you want to send remainders about homework "{{ post.title }}" to all users that have not yet completed it?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
						<form action="{{ url_for('posts.send_remainders', post_id=post.id) }}" method="POST">
							<input class="btn btn-success" type="submit" value="Send">
						</form>
					</div>
				</div>
			</div>
		</div>
		<!-- Modal -->
		<div class="modal fade" id="deleteModal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete post "{{ post.title }}"?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
						<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
							<input class="btn btn-danger" type="submit" value="Delete">
						</form>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if posts.page == page_num %}
				<a class="btn btn-info mb-4" href="{{ url_for('main.homework', page=page_num) }}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-info mb-4" href="{{ url_for('main.homework', page=page_num) }}">{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock content %}

flaskpage/templates/post.html
{% extends "base.html" %}
{% block content %}
	<article class="media content-section">
		<div class="w-100">
			<div class="media">
				<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
				<div class="article-metadata w-100 align-self-center">
					<div class="col-auto row">
						<a class="mr-2" href="{{ url_for('users.account', user_id=post.author.id) }}">{{ post.author.username }}</a>
						<small class="text-dark" style="padding-top: 3px;">Joined on: {{ post.author.year }}</small>
					</div>
					{% if post.author == current_user %}
							<button type="button" class="btn btn-success btn-sm m-0 mb-1" data-toggle="modal" data-target="#remainderModal{{ post.id }}">Send remainders</button>
							<a class="btn btn-primary btn-sm m-0 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
							<button type="button" class="btn btn-danger btn-sm m-0 mb-1" data-toggle="modal" data-target="#deleteModal{{ post.id }}">Delete</button>
					{% endif %}
				</div>
			</div>
			<h2 class=""><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
				<p class="article-content mb-1">{{ post.content }}</p>
				<div class="container pl-0 pr-0">
					<small class="text-dark">Posted on: {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
				<div class="container pl-0 pr-0">
					<small class="text-dark">On subject: {{ post.author.subj }}</small>
				</div>
				<div class="container pl-0 pr-0">
					{% if current_user.op %}
						<small class="text-dark">Completed by: {{ data_count }} of {{ data_total }} student{% if data_total > 1 %}s{% endif %}</small>
					{% else %}
						<small class="text-dark">Completion status: {% if is_comp == 0 %}Not {% endif %}Completed</small>
					{% endif %}
				</div>
		</div>
	</article>
	{% for user in Users %}
		{% set is_comp = done_hw.filter_by(user_id=user.id).count() %}
		{% if post.author == current_user %}
			<article class="media content-section">
		{% else %}
			<article class="media content-section" {% if is_comp == 1 %}style="background-color:#88FF88;"{% else %}style="background-color:#FF6677;"{% endif %}>
		{% endif %}
				<div class="media">
					<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
					<div>
						<div class="col-auto row">
							<a class="mr-2" href="{{ url_for('users.account', user_id=user.id) }}">{{ user.username }}</a>
							{% if user.op %}
								<small class="text-dark" style="padding-top: 3px;">Joined on: {{ user.year }}</small>
							{% else %}
								<small class="text-dark" style="padding-top: 3px;">{{ user.year }}. year of "{{ user.subj }}"</small>
							{% endif %}
						</div>
						<div class="mb-1">
							<form>
								{% if post.author == current_user %}
									<a class="btn{% if is_comp == 1 %} btn-success{% else %} btn-danger{% endif %} btn-sm m-0" href="{{ url_for('posts.post_done', post_id=post.id, user_id=user.id) }}">{% if is_comp == 0 %}Not {% endif %}Completed</a>
								{% else %}
									<small class="text-dark">Completion status: {% if is_comp == 0 %}Not {% endif %}Completed</small>
								{% endif %}
							</form>
						</div>
					</div>
				</div>
		</article>
	{% endfor %}
	<!-- Modal -->
	<div class="modal fade" id="remainderModal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteModalLabel">Are you sure you want to send remainders about homework "{{ post.title }}" to all users that have not yet completed it?</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<form action="{{ url_for('posts.send_remainders', post_id=post.id) }}" method="POST">
						<input class="btn btn-success" type="submit" value="Send">
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- Modal -->
	<div class="modal fade" id="deleteModal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete post "{{ post.title }}"?</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
						<input class="btn btn-danger" type="submit" value="Delete">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

flaskpage/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}